[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer_runs = 44444
via_ir = false
ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
mainnet = "https://ethereum-rpc.publicnode.com"

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = true
